# Generated by Django 5.0.7 on 2024-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medications",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientid", models.IntegerField()),
                ("doctorid", models.IntegerField()),
                ("doctorname", models.CharField(max_length=80)),
                ("medicinename", models.CharField(max_length=80)),
                ("quantity", models.CharField(max_length=80)),
                ("days", models.CharField(max_length=80)),
                ("time", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
