# Generated by Django 5.0.7 on 2024-07-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("user_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("relationship", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="HealthInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("user_id", models.PositiveIntegerField()),
                ("age", models.PositiveIntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("blood_type", models.CharField(max_length=10)),
                ("allergies", models.TextField(blank=True)),
                ("ongoing_medicines", models.TextField(blank=True)),
                ("medical_conditions", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prescrition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientid", models.IntegerField()),
                ("username", models.CharField(max_length=10)),
                ("medicinename", models.CharField(max_length=80)),
                ("quantity", models.CharField(max_length=80)),
                ("days", models.CharField(max_length=80)),
                ("time", models.CharField(max_length=80)),
                ("status", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
