# Generated by Django 5.0.7 on 2024-07-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("mood", models.CharField(max_length=80)),
                ("date", models.CharField(max_length=80)),
            ],
        ),
    ]
