# Generated by Django 5.0.7 on 2024-07-14 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescrition",
            name="username",
            field=models.CharField(
                default=datetime.datetime(2024, 7, 14, 14, 55, 42, 608044),
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
