# Generated by Django 5.0.7 on 2024-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_emergencycontact_healthinfo_prescrition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="user",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="healthinfo",
            name="user",
            field=models.IntegerField(),
        ),
    ]
