# Generated by Django 5.0.7 on 2024-07-14 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_prescrition_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescrition",
            name="status",
            field=models.CharField(
                default=datetime.datetime(2024, 7, 14, 14, 57, 14, 964961),
                max_length=80,
            ),
            preserve_default=False,
        ),
    ]
