# Generated by Django 5.0.7 on 2024-07-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_moodtracker"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyDispatcher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=80)),
                ("emergency_type", models.CharField(max_length=80)),
                ("first_aid_given", models.CharField(max_length=80)),
                ("status", models.CharField(max_length=80)),
            ],
        ),
    ]
