# Generated by Django 5.0.7 on 2024-07-14 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_emergencycontact_user_alter_healthinfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.AlterField(
            model_name="healthinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
