# Generated by Django 5.0.7 on 2024-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_emergencycontact_user_alter_healthinfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthinfo",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
    ]
